export const GET_ALL_PRODUCTS_REQUEST ='GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS ='GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAIL ='GET_ALL_PRODUCTS_FAIL';


export const GET_PRODUCT_BY_NAME_REQUEST = 'GET_PRODUCT_BY_NAME_REQUEST';
export const GET_PRODUCT_BY_NAME_SUCCESS = 'GET_PRODUCT_BY_NAME_SUCCESS';
export const GET_PRODUCT_BY_NAME_FAIL = 'GET_PRODUCT_BY_NAME_FAIL';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL';



export const SORT_AND_FILTER = 'SORT AND_FILTER'

