export const GET_ALL_PRODUCTS_REQUEST ='GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS ='GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAIL ='GET_ALL_PRODUCTS_FAIL';


export const GET_PRODUCT_BY_NAME_REQUEST = 'GET_PRODUCT_BY_NAME_REQUEST';
export const GET_PRODUCT_BY_NAME_SUCCESS = 'GET_PRODUCT_BY_NAME_SUCCESS';
export const GET_PRODUCT_BY_NAME_FAIL = 'GET_PRODUCT_BY_NAME_FAIL';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL';


export const GET_SINGLE_CATEGORY = 'GET_SINGLE_CATEGORY'
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const EDIT_PRODUCT = "EDICT_PRODUCT"

export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"
export const ORDER_BY_PRICE = "ORDER_BY_PRICE"
export const FILTER_BY_PRICE = "FILTER_BY_PRICE"

export const CLEAN_DETAIL = 'CLEAN_DETAIL'

export const GET_REVIEWS_PRODUCT = 'GET_REVIEWS_PRODUCT'
export const GET_REVIEWS_PRODUCT_DETAIL = 'GET_REVIEWS_PRODUCT_DETAIL'
export const CREATE_REVIEW = 'CREATE_REVIEW'
export const CLEAN_REVIEW = 'CLEAN_REVIEW'

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER ='USER_REGISTER';
export const USER_REGISTER_CLEAR = 'USER_REGISTER_CLEAR';
export const GET_USERS = "GET_USERS"
export const GET_USER = "GET_USER";
export const USER_UPDATE = 'USER_UPDATE'


export const ADD_CART = 'ADD_CART'
export const DELETE_ONE_PRODUCT_CART = 'DELETE_ONE_PRODUCT_CART'
export const GET_CART = 'GET_CART'
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART'
export const DELETE_ALL_PRODUCTS_CART = 'DELETE_ALL_PRODUCTS_CART'
export const PAID_CART_TEMPORAL = 'PAID_CART_TEMPORAL'
export const GET_SHOPPING = 'GET_SHOPPING'

export const CLOSE_CART = 'CLOSE_CART';
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

export const ADD_PRODUCT_GUEST = 'ADD_PRODUCT_GUEST'
export const DELETE_ONE_PRODUCT_GUEST = 'DELETE_ONE_PRODUCT_GUEST'
export const SUBSTRACT_PRODUCT_GUEST = 'SUBSTRACT_PRODUCT_GUEST'
export const GET_CART_GUEST = 'GET_CART_GUEST'
export const DELETE_CART_GUEST = 'DELETE_CART_GUEST'