export const GET_ALL_PRODUCTS_REQUEST ='GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS ='GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAIL ='GET_ALL_PRODUCTS_FAIL';


export const GET_PRODUCT_BY_NAME_REQUEST = 'GET_PRODUCT_BY_NAME_REQUEST';
export const GET_PRODUCT_BY_NAME_SUCCESS = 'GET_PRODUCT_BY_NAME_SUCCESS';
export const GET_PRODUCT_BY_NAME_FAIL = 'GET_PRODUCT_BY_NAME_FAIL';

export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAIL = 'GET_PRODUCT_BY_ID_FAIL';


export const GET_SINGLE_CATEGORY = 'GET_SINGLE_CATEGORY'
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const EDIT_PRODUCT = "EDICT_PRODUCT"

export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"
export const ORDER_BY_PRICE = "ORDER_BY_PRICE"
export const FILTER_BY_PRICE = "FILTER_BY_PRICE"

export const CLEAN_DETAIL = 'CLEAN_DETAIL'

export const GET_REVIEWS_PRODUCT = 'GET_REVIEWS_PRODUCT'
export const CREATE_REVIEW = 'CREATE_REVIEW'

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER ='USER_REGISTER';
export const USER_REGISTER_CLEAR = 'USER_REGISTER_CLEAR';
export const GET_USERS = "GET_USERS"
export const GET_USER = "GET_USER"

